### ISSUE TITLE
UI jiggles infinetely if soundfile does not play

### ISSUE THREAD

**Issue by bkimminich** [wurstbrot/shake-logger#2]
I ran the demo today on Win10 with Docker Toolbox (on top of VirtualBox) and port forwarding for `127.0.0.1:3000` and `:8080` to `0.0.0.0:3000` and `:8080`. The UI elements "danced" but the MP3 wasn't played. Also the "dancing" never stopped, which was fun but also slightly annoying... :grinning:

Any idea what I might have missed here? The Juice Shop itself and also the `logger.php` worked just fine.

**Comment by wurstbrot** [comment]
Without internet connection the MP3 can not be downloaded. Maybe, you couldn't download it?

**Comment by wurstbrot** [comment]
As I don't know the licence of the MP3, I am afraid to put it in this repo.

**Comment by bkimminich** [comment]
Maybe, I didn't check that. I was behind a university proxy with settings/rules unknown to me, that's for sure... I'll retry at home and see if it works.

**Comment by bkimminich** [comment]
⚰️
